name: Deploy Hugo site to Pages

on:
  # 在 main 分支的推送觸發
  push:
    branches:
      - main

  # 允許手動觸發
  workflow_dispatch:

# 設定 GITHUB_TOKEN 權限
permissions:
  contents: read
  pages: write
  id-token: write

# 只允許一個部署同時進行
concurrency:
  group: "pages"
  cancel-in-progress: false

# 預設 shell 設定
defaults:
  run:
    shell: bash

jobs:
  # 建置任務
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.148.1
    steps:
      - name: 安裝 Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: 安裝 Dart Sass
        run: sudo snap install dart-sass

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: 設定 Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: 安裝 Node.js 依賴
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: 使用 Hugo 建置
        env:
          # 為了最大向後兼容性
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: 上傳 artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # 部署任務
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
